title: Scalable Modeling – An Event-centric Approach
description: This repository offers a modeling technique for designing scalable systems.
author: Simo Roikonen

baseurl: "/scalablemodeling"
url: "https://roikonen.github.io"

theme: minima

header_text: "Scalable Modeling – An Event-centric Approach"
footer_text: "2025 Simo Roikonen"

bluesky_username: roikonen.bsky.social
linkedin_username: roikonen
github_username: roikonen

