title: Scalable Modeling – An Event-centric Approach
description: This repository offers a modeling technique for designing scalable systems.
author: Simo Roikonen

baseurl: "/scalablemodeling"
url: "https://roikonen.github.io"

theme: minima

header_text: "Scalable Modeling – An Event-centric Approach"
header_pages:
  - README.md
  - about_me.md

footer_text: "2025 Simo Roikonen"

bluesky_username: roikonen
linkedin_username: roikonen
github_username: roikonen

