theme: minima
title: Scalable Modeling – An Event-centric Approach
description: This repository offers a modeling technique for designing scalable systems.
social:
  - platform: github
    user_url: "https://github.com/roikonen"
  - platform: bluesky
    user_url: "https://bsky.app/profile/roikonen.bsky.social"
  - platform: linkedin
    user_url: "https://www.linkedin.com/in/roikonen/"
  - platform: devto
    user_url: "https://dev.to/roikonen"
plugins:
  - jekyll-mathjax
